[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "RubenPari", email = "rubenpari.developer@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}
