[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "RubenPari", email = "rubenpari.developer@gmail.com"},
]
dependencies = [
    "pandas>=1.5.3",
    "autopep8>=2.0.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
